### ISSUE TITLE
Use local installation instead of global installation of Gatsby-cli.

### ISSUE THREAD

**Issue by Phoenix181** [woojiahao/woojiahao.github.io#10]
Global installation of any npm packages is generally discouraged ([source](https://stackoverflow.com/a/41563468)). 

Following that install gatby-cli as dev dependency or a dependency and can use npm scripts to run `gatby develop` or you can use npx ([source](https://stackoverflow.com/a/15157360))

**Comment by woojiahao** [comment]
Where is this stated?

**Comment by woojiahao** [comment]
As this has been discussed on the server, I'll be closing this for now. Thanks!
